name: test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: ruff lint
        run: |
          ruff .
      - name: ruff format
        run: |
          ruff format --check .
      - name: mypy
        run: |
          mypy .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: pytest
        run: |
          pytest -W error tests

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: pytest
        run: |
          pytest -W error test_poopip_e2e.py

  e2e-test-pypy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up PyPy
          run: |
            sudo add-apt-repository -y ppa:pypy/ppa
            sudo apt-get update -qq
            sudo apt-get install -yq pypy3
        - name: Install test dependencies
          run: |
            pypy3 -m pip install --user pytest
        - name: pytest
          run: |
            pypy3 -m pytest -W error test_poopip_e2e.py
